### ISSUE TITLE
Add nfs-common to the default set of packages on the hosts

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-kubernetes-core#24]
Stumbled upon: https://github.com/kubernetes/kubernetes/issues/24687

and could not have NFS volumes in k8s for stateful workloads. Installed nfs-common and works. I think this would be a nice addition to the OOTB experience. 

Bonus: add a relation to the NFS charm to automatically create a NFS service in k8s, so that PV/PVC can be created there.

**Comment by chuckbutler** [comment]
This is resolved in another PR in flight against kubernetes-worker layer. 

https://github.com/juju-solutions/kubernetes/pull/57

Closing this issue here as its being tracked in bundle-canonical-kubernetes already. If there's any information in this bug that needs to be ported over, please cc in the changes here

https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/72
